const siteMenu=document.querySelector('#siteMenu');const siteMenuBtn=document.querySelector('.menu');const siteMenuClose=document.querySelector('#siteMenuClose');function closeSiteMenu(){siteMenu?.classList.remove('open');siteMenu?.setAttribute('aria-hidden','true');document.body.classList.remove('menuOpen')}siteMenuBtn?.addEventListener('click',()=>{siteMenu?.classList.add('open');siteMenu?.setAttribute('aria-hidden','false');document.body.classList.add('menuOpen')});siteMenuClose?.addEventListener('click',closeSiteMenu);siteMenu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeSiteMenu));
const PRODUCT_NAME = "FUNFINS+ Wave / Notch Blade Only";
const BASE_IMAGE = "funfins-type1-red-ferrari.jpg";
const RAIL_PRICES = {"Water Rails":1500000,"U-List":1000000};
const selected={rail:"Water Rails",stiffness:"Medium",color:"Red Ferrari",colorImage:BASE_IMAGE,qty:1};
const $=s=>document.querySelector(s);
const money=n=>"Rp "+n.toLocaleString("id-ID");
const selectedPrice=()=>RAIL_PRICES[selected.rail];
function updateProductPrice(){const p=$(".price");if(p)p.textContent=money(selectedPrice());}
function updateRail(button){document.querySelectorAll(".variantOption").forEach(x=>x.classList.remove("active"));button.classList.add("active");selected.rail=button.dataset.rail;$("#railValue").textContent=selected.rail.toUpperCase();updateProductPrice();updateSummary();}
function updateStiffness(button){document.querySelectorAll(".stiffnessOption").forEach(x=>x.classList.remove("active"));button.classList.add("active");selected.stiffness=button.dataset.stiffness;$("#stiffnessValue").textContent=selected.stiffness.toUpperCase();updateSummary();}
function updateSummary(){[["#summaryColor",selected.color],["#summaryRail",selected.rail],["#summaryStiffness",selected.stiffness],["#summaryQty",selected.qty],["#summaryTotal",money(selectedPrice()*selected.qty)]].forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v;});}
function openOrder(){updateSummary();$("#orderModal")?.classList.add("open");document.body.classList.add("modalOpen");}
function closeOrder(){$("#orderModal")?.classList.remove("open");document.body.classList.remove("modalOpen");}
function changeQty(amount){selected.qty=Math.max(1,selected.qty+amount);updateSummary();}
function confirmOrder(){const total=selectedPrice()*selected.qty;const message="Halo FUNFINS,%0A%0A*Saya ingin melakukan konfirmasi pesanan:*%0A%0AProduk: "+encodeURIComponent(PRODUCT_NAME)+"%0ARail: "+encodeURIComponent(selected.rail)+"%0AStiffness: "+encodeURIComponent(selected.stiffness)+"%0AColor: "+encodeURIComponent(selected.color)+"%0AQuantity: "+selected.qty+"%0AHarga/unit: "+encodeURIComponent(money(selectedPrice()))+"%0ATotal: "+encodeURIComponent(money(total))+"%0A%0AMohon konfirmasi ketersediaan dan proses pesanannya.%0A%0ANama:%0AAlamat:%0ACatatan:";window.open("https://wa.me/6289638142670?text="+message,"_blank");}
document.querySelectorAll(".colorOption").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".colorOption").forEach(x=>x.classList.remove("active"));button.classList.add("active");selected.color=button.dataset.color;selected.colorImage=button.dataset.image;document.querySelectorAll(".productPhoto img, .summaryImage img").forEach(img=>{img.style.opacity=".35";setTimeout(()=>{img.src=selected.colorImage;img.alt=PRODUCT_NAME+" — "+selected.color;img.style.opacity="1";},120);});$("#colorValue").textContent=selected.color.toUpperCase();const sc=$("#specColor");if(sc)sc.textContent=selected.color.toUpperCase();updateSummary();}));
document.querySelectorAll(".variantOption").forEach(b=>b.addEventListener("click",()=>updateRail(b)));
document.querySelectorAll(".stiffnessOption").forEach(b=>b.addEventListener("click",()=>updateStiffness(b)));
$("#checkoutBtn")?.addEventListener("click",openOrder);$("#headerOrder")?.addEventListener("click",openOrder);$("#orderClose")?.addEventListener("click",closeOrder);$("#qtyMinus")?.addEventListener("click",()=>changeQty(-1));$("#qtyPlus")?.addEventListener("click",()=>changeQty(1));$("#confirmOrder")?.addEventListener("click",confirmOrder);$("#orderModal")?.addEventListener("click",e=>{if(e.target===$("#orderModal"))closeOrder();});addEventListener("keydown",e=>{if(e.key==="Escape")closeOrder();});addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;const bar=$(".progress");if(bar)bar.style.width=(max>0?scrollY/max*100:0)+"%";document.querySelector("header")?.classList.toggle("scrolled",scrollY>30);});addEventListener("load",()=>setTimeout(()=>$(".loader")?.classList.add("done"),900));$("#railValue").textContent=selected.rail.toUpperCase();$("#stiffnessValue").textContent=selected.stiffness.toUpperCase();updateProductPrice();updateSummary();
